### ISSUE TITLE
Site not deploying - GitHub host key changed

### ISSUE THREAD

**Issue by tombruijn** [railsgirls/railsgirls.com#2163]
I think this website is currently not being deployed every 5 minutes, [like the README states](https://github.com/railsgirls/railsgirls/blob/3ff87a846d5c7610f636ed38f52ed83f2bb03ed4/README.md#L14).

GitHub changed their host key some time ago: https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

The last updated at file now returns that same error: http://railsgirls.com/deploy.txt
Which prevents Git from pulling the latest changes and the server not deploying the changes.

I've reached out to @ksaa, who @vesan [mentioned manages the hosting](https://github.com/railsgirls/railsgirls.github.io/issues/516#issuecomment-1484078374), but I haven't heard back yet.

## The Git(Hub) error

```
01/04/2023 09:15:01 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
01/04/2023 09:15:01 @ WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED! @
01/04/2023 09:15:01 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
01/04/2023 09:15:01 IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
01/04/2023 09:15:01 Someone could be eavesdropping on you right now (man-in-the-middle attack)!
01/04/2023 09:15:01 It is also possible that a host key has just been changed.
01/04/2023 09:15:01 The fingerprint for the RSA key sent by the remote host is
01/04/2023 09:15:01 d5:2c:63:d9:bc:75:9d:de:b1:4e:36:28:9f:7a:9c:39.
01/04/2023 09:15:01 Please contact your system administrator.
01/04/2023 09:15:01 Add correct host key in /home/awesome/.ssh/known_hosts to get rid of this message.
01/04/2023 09:15:01 Offending RSA key in /home/awesome/.ssh/known_hosts:1
01/04/2023 09:15:01 remove with: ssh-keygen -f "/home/awesome/.ssh/known_hosts" -R github.com
01/04/2023 09:15:01 RSA host key for github.com has changed and you have requested strict checking.
01/04/2023 09:15:01 Host key verification failed.
01/04/2023 09:15:01 fatal: Could not read from remote repository.
01/04/2023 09:15:01 
01/04/2023 09:15:01 Please make sure you have the correct access rights
01/04/2023 09:15:01 and the repository exists.
```

**Comment by hsbt** [comment]
I deployed this repository to https://railsgirls.org/ now.

**Comment by hsbt** [comment]
@ksaa Thanks for maintaining railsgirls.com while long years. We move to this site railsgirls.org and github-pages. Feel free to remove domain configuration and shutdown VPS server.

**Comment by tombruijn** [comment]
It would still be a good idea to keep the railsgirls.com domain. It's the domain that's been used for 10+ years, so I assume a lot of other sites link to it.
I'm not against using railsgirls.org, but we should redirect railsgirls.com to railsgirls.org.

**Comment by tombruijn** [comment]
And what do we do with guides.railsgirls.com? We should move that over to guides.railsgirls.org. But we should redirect .com to .org as well.

**Comment by tombruijn** [comment]
@hsbt It would still be a good idea to keep the railsgirls.com domain. It's the domain that's been used for 10+ years, so I assume a lot of other sites link to it.
I'm not against using railsgirls.org, but we should redirect railsgirls.com to railsgirls.org.

The same is true for guides.railsgirls.com, If we want to use the .org domain from now on, we should move it over to guides.railsgirls.org. Meanwhile the .com should redirect to .org as well.

I'll reach out to @ksaa on Twitter, no response via email so far, to see if he can help with the redirect or transfer the domain.

**Comment by hsbt** [comment]
@tombruijn Thanks for your comment. We can prepare redirector to guides.railsgirls.com with github-pages.

**Comment by luhova** [comment]
@hsbt stopping by just to say thank you! :heart: As part of a team currently organizing an event next month, I am grateful the deploys are working again now. I agree with @tombruijn that we should redirect .com to .org. :raised_hands:

**Comment by ksaa** [comment]
Hi! Thank you all for doing this. My previous setup was bit hacky. I can redirect the railsgirls.com to GitHub pages

**Comment by tombruijn** [comment]
If we can change the DNS for railsgirls.com, I suggest we do that. Everything links to that domain, search engine results and other websites. That way people don't arrive at broken links.

If we want to move everything over to another domain at some point, let's create a redirect app or AWS lambda function to link all existing pages to the new domain. For now that should not be necessary if @ksaa can update the railsgirls.com DNS to point to GitHub pages for railsgirls.com and guides.railsgirls.com. I've shared the instructions for that :)

**Comment by hsbt** [comment]
@ksaa Can you update your DNS configuration with the following?

```
railsgirls.com A 185.199.108.153, 185.199.109.153, 185.199.110.153, 185.199.111.153
guides.railsgirls.com CNAME railsgirls.github.io.
```

After that, I'll roleback their configuration of github from `.org` to `.com`.

**Comment by tombruijn** [comment]
The DNS has been updated for the railsgirls.com and guides.railsgirls.com domains.

I've tried updating the domain for GitHub Pages, but I'm running into the error below.

> The custom domain `railsgirls.com` is already taken. If you are the owner of this domain, check out https://docs.github.com/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages for information about how to verify and release this domain.

Looks like some other repository has claimed the domain or something. No repo on the Rails Girls organization is currently using it though.

I've asked @ksaa to add the [domain verification record mentioned in the guide](https://docs.github.com/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages), and I'll keep an eye on verifying it. When verified, we can change the domain on the repositories.

**Comment by hsbt** [comment]
@tombruijn Did you already update the verified domain configuration? I confused what is status for this verification.

**Comment by hsbt** [comment]
@ksaa Can you update TXT recode of `_github-challenge-railsgirls-org.railsgirls.com` to "f3d890a0a6"?

**Comment by tombruijn** [comment]
@hsbt the verification we need for GitHub pages to use the domain can be found here: https://github.com/organizations/railsgirls/settings/pages
I've shared the instructions with Karri, and I'm waiting for the DNS changes to be made.

This is a different type of domain verification than the one you described. I think that's for showing the domain as verified on the GitHub profile of the rails girls organization. It will show something like this:
![image](https://user-images.githubusercontent.com/282402/231635466-75b9e9ce-ac4c-4eb3-a6b2-e63ec75971ea.jpeg)

**Comment by hsbt** [comment]
Got it. Thanks.

Can you share your work in this issue or something? I'm maintaining railsgirls.com and guides.railsgirls.com while 10years+. I'm confused every morning because you did change our site without my confirmation.

**Comment by tombruijn** [comment]
> Can you share your work in this issue or something?

That's what I'm doing, but I can't do a lot. I'm mostly just communicating with Karri about the DNS changes for the .com domain.

> I'm maintaining railsgirls.com and guides.railsgirls.com while 10years+. I'm confused every morning because you did change our site without my confirmation.

I haven't changed anything on railsgirls.com/org. Other than adding workshops I'm organizing and moving past events to the past events list.

I have worked more intensively on the guides 2 months ago. I sent PRs for a lot of the changes. If you want, I can send in PRs for every change, but some changes felt more like an extension of other PRs or felt too small for a PR.

**Comment by tombruijn** [comment]
@hsbt Could you kindly clarify something for me? I have noticed that I am no longer an owner of the Rails Girls organization, along with some of my fellow organizers. As a result, I am unable to assist with verifying the domain for the GitHub Pages move. I was wondering if there was a specific reason for this change, and if there are any concerns about my continued involvement in maintaining the Rails Girls projects. I am eager to contribute to improving the guides and potentially the website, and I would appreciate any guidance you can provide. Thank you.

**Comment by vesan** [comment]
@tombruijn you should have admin rights which is the highest there is. Just verified.

**Comment by tombruijn** [comment]
Hi @vesan, yes, I see am part of the admin team. The domain verification for GitHub Pages though is in the organization settings here: https://github.com/organizations/railsgirls/settings/pages
Yesterday, I was able to start the verification process in the organization settings panel, but I now I no longer have access to restart the verification process.

**Comment by hsbt** [comment]
I filed https://github.com/railsgirls/railsgirls.org/issues/2163#issuecomment-1506063270 about instructions to verify `railsgirls.com`.

@ksaa Could you update it?

**Comment by ksaa** [comment]
I have these set up now but personally I haven't seen the DNS propagate yet 
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/105902/231935646-9d876c3e-b45b-4a80-a0b3-1f9b882522a8.png">

**Comment by ksaa** [comment]
The domain is verified now and I think the DNS fine. Problem now is that GitHub pages settings are not correct. Pages are served under railsgirls.org so .com now points to nothing on the GitHub side.

**Comment by ksaa** [comment]
I'll just point the DNS for the old server now so the site is online while you guys figure out the GitHub side. I fixed the git pull so now it updates again every 5mins http://railsgirls.com/deploy.txt

**Comment by hsbt** [comment]
Thanks. I confirmed to `railsgirls.com` is now verified for github pages.

>The domain is verified now and I think the DNS fine. Problem now is that GitHub pages settings are not correct. Pages are served under railsgirls.org so .com now points to nothing on the GitHub side.

We still can't change `.org` to `.com` because `The custom domain `railsgirls.com` is already taken. ` error. It seems GitHub issue. I'll contact GitHub support.

@ksaa Can you update DNS configuration for `railsgirls.com` after contacting GitHub issue? Thanks.

**Comment by hsbt** [comment]
and Can you update `_github-challenge-railsgirls-org.railsgirls.com` to `f3d890a0a6` as TXT record? Unfortunately I removed this configuration while investigating domain issue.

**Comment by hsbt** [comment]
@tombruijn 

>I am eager to contribute to improving the guides and potentially the website, and I would appreciate any guidance you can provide.

Thanks to your contribution. You can still add/update this repository and guides.

I removed owner grant from you because I hope to unify communication path for domain configuration. Unfortunately, I still didn't know what you share update instruction to ksss.

**Comment by hsbt** [comment]
@ksaa Could you add the following TXT record and https://github.com/railsgirls/railsgirls.org/issues/2163#issuecomment-1507905043 ?

hostname: `_github-pages-challenge-railsgirls.guides.railsgirls.com`
value: `e0129682d1e5a2d304107748c5bd7e`

GitHub Support released `railsgirls.com`. We can update `railsgirls.com` for GitHub pages now. But we also need to release request for `guides.railsgirls.com`. GitHub support say you need to verify each subdomain for GitHub pages.

**Comment by ksaa** [comment]
They are now verified 
<img width="854" alt="image" src="https://user-images.githubusercontent.com/105902/232101148-072610e5-f597-4737-92a1-acefe364d2c4.png">

**Comment by hsbt** [comment]
Thanks @ksaa. I requested to release `guides.railsgirls.com` to GitHub support.

**Comment by vesan** [comment]
Hmm… The railsgirls.com is serving the ” There isn't a GitHub Pages site here.” page again. It did start working earlier.

@hsbt Should we now change this repo to start pointing to the .com domain? And redirect .org to .com?

**Comment by ksaa** [comment]
Also need the https setup for railsgirls.com before we can switch the domain. I tried changing the this repo's Pages setup to railsgirls.com but it doesn't work because there is no cert

**Comment by vesan** [comment]
Github is supposed to provision the cert automatically https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

**Comment by hsbt** [comment]
@vesan I update the GitHub Pages configuration at this repository. railsgirls.com and its certificate are working fine now.

We also need to update `guides.railsgirls.com` configuration. But It's reserved by GitHub. 

@ksaa Can you keep the current DNS configuration? I'll work them in the next week with GitHub support.

**Comment by hsbt** [comment]
I updated and deployed https://railsgirls.com and https://guides.railsgirls.com. They are everything fine. I also added redirect from *.railsgirls.org to *.railsgirls.com. I keep this domain.

@tombruijn @vesan @ksaa Thanks for your help.
